"""Template rendering: ReportContext in, Markdown or HTML out.

Markdown is the canonical artifact (generated by the orchestrator); HTML is
styled and self-contained for browser viewing and as the input to PDF export.
HTML templates autoescape — model-produced text is untrusted content.
"""

from __future__ import annotations

from jinja2 import Environment, PackageLoader

from reports.context import ReportContext


def _autoescape(template_name: str | None) -> bool:
    return template_name is not None and ".html" in template_name


_env = Environment(
    loader=PackageLoader("reports", "templates"),
    autoescape=_autoescape,
    trim_blocks=False,
    keep_trailing_newline=True,
)
_env.filters["cite"] = lambda numbers: "".join(f"[{n}]" for n in numbers)


def render_markdown(context: ReportContext) -> str:
    return _env.get_template("memo.md.j2").render(ctx=context)


def render_html(context: ReportContext) -> str:
    return _env.get_template("memo.html.j2").render(ctx=context)
